export const mockEvents = [
  {
    id: "1",
    title: "Tech Summit 2025",
    description:
      "Annual technology conference featuring the latest innovations and research presentations from ASTU students and faculty.",
    date: "2025-10-15T18:00:00",
    time: "6:00 PM - 9:00 PM",
    location: "Main Auditorium",
    category: "technology",
    image: "/placeholder.svg?height=400&width=800&text=Tech+Summit",
    attendees: 120,
    capacity: 200,
    organizer: "Computer Science Department",
  },
  {
    id: "2",
    title: "Cultural Night",
    description:
      "Celebrating diverse cultures through performances, exhibitions, and traditional food from different regions of Ethiopia.",
    date: "2025-01-05T17:00:00",
    time: "5:00 PM - 10:00 PM",
    location: "University Square",
    category: "cultural",
    image: "/placeholder.svg?height=400&width=800&text=Cultural+Night",
    attendees: 200,
    capacity: 300,
    organizer: "Student Union",
  },
  {
    id: "3",
    title: "Coding Workshop",
    description:
      "Learn the basics of web development in this hands-on workshop. Perfect for beginners and intermediate programmers.",
    date: "2025-11-10T14:00:00",
    time: "2:00 PM - 5:00 PM",
    location: "Computer Lab 3",
    category: "academic",
    image: "/placeholder.svg?height=400&width=800&text=Coding+Workshop",
    attendees: 30,
    capacity: 50,
    organizer: "Programming Club",
  },
  {
    id: "4",
    title: "Career Fair 2025",
    description:
      "Connect with potential employers, explore internship opportunities, and get career advice from industry professionals.",
    date: "2025-09-20T09:00:00",
    time: "9:00 AM - 4:00 PM",
    location: "University Hall",
    category: "career",
    image: "/placeholder.svg?height=400&width=800&text=Career+Fair",
    attendees: 150,
    capacity: 300,
    organizer: "Career Development Office",
  },
  {
    id: "5",
    title: "Annual Sports Tournament",
    description:
      "Compete in various sports including football, basketball, volleyball, and athletics. Open to all students and faculty.",
    date: "2025-03-15T08:00:00",
    time: "8:00 AM - 6:00 PM",
    location: "Sports Complex",
    category: "sports",
    image: "/placeholder.svg?height=400&width=800&text=Sports+Tournament",
    attendees: 200,
    capacity: 500,
    organizer: "Sports Department",
  },
  {
    id: "6",
    title: "Art Exhibition",
    description:
      "Showcasing creative works from ASTU students and local artists. Includes paintings, sculptures, photography, and digital art.",
    date: "2025-04-10T10:00:00",
    time: "10:00 AM - 7:00 PM",
    location: "Art Gallery",
    category: "arts",
    image: "/placeholder.svg?height=400&width=800&text=Art+Exhibition",
    attendees: 80,
    capacity: 150,
    organizer: "Fine Arts Club",
  },
  {
    id: "7",
    title: "Research Symposium",
    description:
      "Annual event where students and faculty present their research findings and ongoing projects across various disciplines.",
    date: "2025-05-25T09:00:00",
    time: "9:00 AM - 5:00 PM",
    location: "Conference Center",
    category: "academic",
    image: "/placeholder.svg?height=400&width=800&text=Research+Symposium",
    attendees: 100,
    capacity: 200,
    organizer: "Research Department",
  },
  {
    id: "8",
    title: "Entrepreneurship Workshop",
    description:
      "Learn how to turn your ideas into successful businesses. Featuring successful entrepreneurs and startup founders.",
    date: "2025-06-12T13:00:00",
    time: "1:00 PM - 5:00 PM",
    location: "Business School",
    category: "career",
    image: "/placeholder.svg?height=400&width=800&text=Entrepreneurship+Workshop",
    attendees: 60,
    capacity: 100,
    organizer: "Innovation Hub",
  },
  {
    id: "9",
    title: "Music Festival",
    description:
      "A day of live music performances featuring student bands, local musicians, and special guest performers.",
    date: "2025-07-08T16:00:00",
    time: "4:00 PM - 11:00 PM",
    location: "Amphitheater",
    category: "cultural",
    image: "/placeholder.svg?height=400&width=800&text=Music+Festival",
    attendees: 250,
    capacity: 400,
    organizer: "Music Club",
  },
]
